"""Artifact storage for Ask AI agent runs — Phase 3 v1.

Artifacts (files generated by the sandbox tool) are stored content-addressed
on the backend storage volume under ``ask_ai_artifacts/`` with metadata in
the Mongo ``ask_ai_artifacts`` collection. Access is always re-checked
against the owning user before a byte is served.
"""

from __future__ import annotations

import hashlib
import logging
import mimetypes
import os
import shutil
import uuid
from datetime import datetime, timezone

from ...config import settings

_log = logging.getLogger(__name__)

_COLLECTION = "ask_ai_artifacts"

_ALLOWED_MIME_PREFIXES = (
    "text/", "image/", "application/pdf", "application/json",
    "application/vnd.openxmlformats-officedocument.",  # pptx/xlsx/docx
)
_DEFAULT_MIME = "application/octet-stream"


def _root() -> str:
    root = os.path.join(str(settings.storage_dir), "ask_ai_artifacts")
    os.makedirs(root, exist_ok=True)
    return root


_EXT_MIME = {
    ".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".md": "text/markdown",
    ".csv": "text/csv",
}


def guess_mime(name: str) -> str:
    ext = os.path.splitext(name)[1].lower()
    if ext in _EXT_MIME:
        return _EXT_MIME[ext]
    mime = mimetypes.guess_type(name)[0] or _DEFAULT_MIME
    if mime == "text/html":
        return "text/html"
    if any(mime.startswith(p) for p in _ALLOWED_MIME_PREFIXES):
        return mime
    return _DEFAULT_MIME


async def save_artifact(
    mongo_db,
    *,
    user_id: int,
    conversation_id: str | None,
    provider: str,
    src_path: str,
    name: str,
) -> dict | None:
    """Move a sandbox output file into the store; return public metadata."""
    try:
        sha = hashlib.sha256()
        with open(src_path, "rb") as fh:
            for block in iter(lambda: fh.read(1 << 20), b""):
                sha.update(block)
        digest = sha.hexdigest()
        size = os.path.getsize(src_path)
        artifact_id = uuid.uuid4().hex
        ext = os.path.splitext(name)[1][:12]
        dest = os.path.join(_root(), f"{digest}{ext}")
        if not os.path.exists(dest):
            shutil.move(src_path, dest)
        else:
            os.unlink(src_path)
        meta = {
            "_id": artifact_id,
            "user_id": user_id,
            "conversation_id": conversation_id,
            "provider": provider,
            "name": name,
            "mime": guess_mime(name),
            "size": size,
            "sha256": digest,
            "path": dest,
            "created_at": datetime.now(timezone.utc),
        }
        if mongo_db is not None:
            await mongo_db[_COLLECTION].insert_one(meta)
        return {"id": artifact_id, "name": name, "mime": meta["mime"], "size": size}
    except Exception as exc:
        _log.warning("save_artifact failed: %s", exc)
        return None


async def get_artifact(mongo_db, artifact_id: str, user_id: int) -> dict | None:
    """Metadata for one artifact, only if owned by ``user_id``."""
    if mongo_db is None:
        return None
    try:
        return await mongo_db[_COLLECTION].find_one({"_id": artifact_id, "user_id": user_id})
    except Exception as exc:
        _log.warning("get_artifact failed: %s", exc)
        return None
