"""MongoDB document models for Ask AI conversation persistence.

Four collections:
  ask_ai_users              — one doc per Postgres user, links user identity
  ask_ai_conversations      — conversation metadata + active scope
  ask_ai_conversation_history — per-turn message history
  ask_ai_turn_runs          — one doc per model run per turn (candidates grid)
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


def _now() -> datetime:
    return datetime.now(timezone.utc)


# ── Scope models ──────────────────────────────────────────────────────────────


class ScopedDocument(BaseModel):
    """A document currently in the active conversation scope."""

    document_id: int
    title: str


class ScopedClass(BaseModel):
    """A document class currently in the active conversation scope."""

    class_id: int
    class_name: str
    document_ids: list[int] = Field(default_factory=list)


class ActiveScope(BaseModel):
    """The current retrieval scope for a conversation.

    An empty scope means vault-wide search (company KB) is used.
    """

    documents: list[ScopedDocument] = Field(default_factory=list)
    classes: list[ScopedClass] = Field(default_factory=list)

    def is_empty(self) -> bool:
        return not self.documents and not self.classes

    def all_document_ids(self) -> set[int]:
        """Return the full set of document IDs covered by this scope."""
        ids: set[int] = set()
        for d in self.documents:
            ids.add(d.document_id)
        for c in self.classes:
            ids.update(c.document_ids)
        return ids


# ── Collection models ──────────────────────────────────────────────────────────


class MongoUser(BaseModel):
    """One record per Postgres user_id in ask_ai_users collection."""

    model_config = ConfigDict(extra="ignore")

    postgres_user_id: int
    name: str = ""
    email: str = ""
    google_drive_connected: bool = False
    google_drive_email: str | None = None
    # Token stored as dict (encrypted at rest in production; plain for dev)
    google_drive_token: dict | None = None
    created_at: datetime = Field(default_factory=_now)
    updated_at: datetime = Field(default_factory=_now)



class MongoConversation(BaseModel):
    """One record per conversation in ask_ai_conversations collection.

    ``_id`` is a UUID string generated by the repository.
    """

    id: str = Field(alias="_id")
    user_id: int
    title: str = "New Conversation"
    created_at: datetime = Field(default_factory=_now)
    last_message_at: datetime = Field(default_factory=_now)
    # Active retrieval scope — updated with each scoped mention
    active_scope: ActiveScope = Field(default_factory=ActiveScope)
    # Message _id after which history is loaded (scope boundary reset on scope change)
    scope_start_message_id: str | None = None
    # Source configuration — company_kb is ALWAYS True; drive is opt-in per turn
    company_kb_enabled: bool = True
    google_drive_enabled: bool = False
    # Conversation DAG (spec §2.1): parents this conversation was branched from
    parent_ids: list[str] = Field(default_factory=list)
    # [{conversation_id, turn_message_id, provider, model_id}] — the accepted
    # answers this branch was continued from ("CONTINUED FROM Gemini + Claude")
    branched_from: list[dict] = Field(default_factory=list)
    # Model set chosen at branch time; None = whatever the UI has enabled
    enabled_models: list[dict] | None = None

    class Config:
        populate_by_name = True


class SourcesUsed(BaseModel):
    """Which sources were actually used in a specific conversation turn."""

    company_kb: bool = False
    google_drive: bool = False


class RunMetrics(BaseModel):
    """Server-side metrics for one model run (card footer)."""

    tokens_in: int = 0
    tokens_out: int = 0
    tokens_estimated: bool = True
    cost_usd: float = 0.0
    latency_ms: int = 0


class MongoTurnRun(BaseModel):
    """One record per model run per turn in ask_ai_turn_runs collection.

    Every candidate answer of the comparison grid is persisted, whether or
    not it is later selected. ``turn_message_id`` is the _id of the user
    message that started the turn.
    """

    id: str = Field(alias="_id")
    conversation_id: str
    turn_message_id: str
    user_id: int
    provider: str
    model_id: str
    display_version: str = ""
    reasoning: str = "none"
    body: str = ""
    status: Literal["ok", "error"] = "ok"
    tool_events: list[dict] = Field(default_factory=list)
    artifacts: list[dict] = Field(default_factory=list)
    passed_from: list[str] = Field(default_factory=list)
    metrics: RunMetrics = Field(default_factory=RunMetrics)
    selected: bool = False
    created_at: datetime = Field(default_factory=_now)

    class Config:
        populate_by_name = True


class MongoHistoryMessage(BaseModel):
    """One record per conversation turn in ask_ai_conversation_history collection.

    ``_id`` is a UUID string generated by the repository.
    """

    id: str = Field(alias="_id")
    conversation_id: str
    user_id: int
    role: Literal["user", "assistant"]
    content: str
    # Set when this message was copied from a parent conversation at branch time
    inherited_from: str | None = None
    # Model attribution + metrics for selected assistant answers (v2)
    provider: str | None = None
    model_id: str | None = None
    metrics: RunMetrics | None = None
    # Snapshot of active_scope at the time this message was sent/received
    scope_snapshot: ActiveScope = Field(default_factory=ActiveScope)
    sources_used: SourcesUsed = Field(default_factory=SourcesUsed)
    created_at: datetime = Field(default_factory=_now)

    class Config:
        populate_by_name = True
